name: system-services
services:
  cloudflared:
    extends:
      file: services/cloudflared/docker-compose.yml
      service: cloudflared
  traefik:
    extends:
      file: services/traefik/docker-compose.yml
      service: traefik
  traefik-forward-auth:
    extends:
      file: services/traefik-forward-auth/docker-compose.yml
      service: traefik-forward-auth
  pocket-id:
    extends:
      file: services/pocket-id/docker-compose.yml
      service: pocket-id
  adguardhome:
    extends:
      file: services/adguardhome/docker-compose.yml
      service: adguardhome
  pihole:
    extends:
      file: services/pihole/docker-compose.yml
      service: pihole

networks:
  services:
    external: true
