name: services
services:
  website:
    extends:
      file: services/website/docker-compose.yml
      service: website
  tududi:
    extends:
      file: services/tududi/docker-compose.yml
      service: tududi
  vaultwarden:
    extends:
      file: services/vaultwarden/docker-compose.yml
      service: vaultwarden
  searxng:
    extends:
      file: services/searxng/docker-compose.yml
      service: searxng
  trilium:
    extends:
      file: services/trilium/docker-compose.yml
      service: trilium
  homarr:
    extends:
      file: services/homarr/docker-compose.yml
      service: homarr

networks:
  frontend:
    external: true
  backend:
    external: true
