name: databases
services:
  redis:
    extends:
      file: services/databases/redis/docker-compose.yml
      service: redis
  qdrant:
    extends:
      file: services/databases/qdrant/docker-compose.yml
      service: qdrant
  mindsdb:
    extends:
      file: services/databases/mindsdb/docker-compose.yml
      service: mindsdb
  mariadb:
    extends:
      file: services/databases/mariadb/docker-compose.yml
      service: mariadb

networks:
  services:
    external: true
