name: ai-services
services:
  openwebui:
    extends:
      file: services/openwebui/docker-compose.yml
      service: openwebui
  n8n:
    extends:
      file: services/n8n/docker-compose.yml
      service: n8n
  n8n-task-runners:
    extends:
      file: services/n8n/docker-compose.yml
      service: task-runners
  docling:
    extends:
      file: services/docling/docker-compose.yml
      service: docling
  perplexica:
    extends:
      file: services/perplexica/docker-compose.yml
      service: perplexica
  clawdbot:
    extends:
      file: services/clawdbot/docker-compose.yml
      service: clawdbot

networks:
  services:
    external: true
