name: databases
services:
  redis:
    extends:
      file: services/databases/redis/docker-compose.yml
      service: redis
  qdrant:
    extends:
      file: services/databases/qdrant/docker-compose.yml
      service: qdrant
  mindsdb:
    extends:
      file: services/mindsdb/docker-compose.yml
      service: mindsdb

networks:
  services:
    external: true
