name: monitoring
services:
  arcane:
    extends:
      file: services/arcane/docker-compose.yml
      service: arcane
  dozzle:
    extends:
      file: services/dozzle/docker-compose.yml
      service: dozzle
  uptime-kuma:
    extends:
      file: services/uptime-kuma/docker-compose.yml
      service: uptime-kuma
  whoami:
    extends:
      file: services/whoami/docker-compose.yml
      service: whoami

networks:
  services:
    external: true
