name: services
services:
  homarr:
    extends:
      file: services/homarr/docker-compose.yml
      service: homarr
  website:
    extends:
      file: services/website/docker-compose.yml
      service: website
  vaultwarden:
    extends:
      file: services/vaultwarden/docker-compose.yml
      service: vaultwarden
  searxng:
    extends:
      file: services/searxng/docker-compose.yml
      service: searxng
  trilium:
    extends:
      file: services/trilium/docker-compose.yml
      service: trilium
  tududi:
    extends:
      file: services/tududi/docker-compose.yml
      service: tududi
  filebrowser:
    extends:
      file: services/filebrowser/docker-compose.yml
      service: filebrowser
  pairdrop:
    extends:
      file: services/pairdrop/docker-compose.yml
      service: pairdrop
  docling:
    extends:
      file: services/docling/docker-compose.yml
      service: docling
  excalidraw:
    extends:
      file: services/excalidraw/docker-compose.yml
      service: excalidraw

networks:
  services:
    external: true
