name: services
services:
  homarr:
    extends:
      file: services/homarr/docker-compose.yml
      service: homarr
  website:
    extends:
      file: development/website/docker-compose.yml
      service: website
  vaultwarden:
    extends:
      file: services/vaultwarden/docker-compose.yml
      service: vaultwarden
  searxng:
    extends:
      file: services/searxng/docker-compose.yml
      service: searxng
  trilium:
    extends:
      file: services/trilium/docker-compose.yml
      service: trilium
  filebrowser:
    extends:
      file: services/filebrowser/docker-compose.yml
      service: filebrowser
  pairdrop:
    extends:
      file: services/pairdrop/docker-compose.yml
      service: pairdrop
  excalidraw:
    extends:
      file: services/excalidraw/docker-compose.yml
      service: excalidraw
  it-tools:
    extends:
      file: services/it-tools/docker-compose.yml
      service: it-tools

networks:
  services:
    external: true
