name: services
services:
  excalidraw:
    extends:
      file: services/excalidraw/docker-compose.yml
      service: excalidraw
  filebrowser:
    extends:
      file: services/filebrowser/docker-compose.yml
      service: filebrowser
  homarr:
    extends:
      file: services/homarr/docker-compose.yml
      service: homarr
  it-tools:
    extends:
      file: services/it-tools/docker-compose.yml
      service: it-tools
  pairdrop:
    extends:
      file: services/pairdrop/docker-compose.yml
      service: pairdrop
  searxng:
    extends:
      file: services/searxng/docker-compose.yml
      service: searxng
  trilium:
    extends:
      file: services/trilium/docker-compose.yml
      service: trilium
  vaultwarden:
    extends:
      file: services/vaultwarden/docker-compose.yml
      service: vaultwarden
  seafile:
    extends:
      file: services/seafile/docker-compose.yml
      service: seafile
  website:
    extends:
      file: development/website/docker-compose.yml
      service: website

networks:
  services:
    external: true
