services:
  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: ghcr.io/italypaleale/traefik-forward-auth:4
    volumes:
      - /home/endo/Docker/services/traefik-forward-auth/config/config.yml:/etc/traefik-forward-auth/config.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - services
    restart: unless-stopped
