server:
  hostname: # "auth.<DOMAIN>"

cookies:
  domain: # "<DOMAIN>"

defaultPortal: "main"

portals:
  - name: "main"
    providers:
      - pocketID:
          endpoint: # "https://pocket-id.<DOMAIN>"
          clientID: # "<POCKETID_ID>"
          clientSecret: # "<POCKETID_SECRET>"
