services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    volumes:
      - ./config:/etc/cloudflared
    networks:
      - services
    restart: unless-stopped