services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./config:/etc/searxng:rw
    environment:
      - SEARXNG_REDIS_URL=${REDIS_URL}/${REDIS_DB_SEARCH}
      - SEARXNG_SECRET=${SEARXNG_SECRET}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${DOMAIN}`)"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
      - "traefik.http.routers.searxng.middlewares=auth@file"
    networks:
      - services
    restart: unless-stopped
