services:
  mindsdb:
    container_name: mindsdb
    image: mindsdb/mindsdb
    volumes:
      - ./data:/root/mdb_storage
    environment:
      - MKL_SERVICE_FORCE_INTEL=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mindsdb.rule=Host(`mindsdb.${DOMAIN}`)"
      - "traefik.http.routers.mindsdb.middlewares=auth@file,mindsdb-headers"
      - "traefik.http.services.mindsdb.loadbalancer.server.port=47334"
      - "traefik.http.middlewares.mindsdb-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.mindsdb-headers.headers.customrequestheaders.X-Forwarded-Host=mindsdb.${DOMAIN}"
    networks:
      - services
    restart: unless-stopped
