services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.${DOMAIN}`)"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
    networks:
      - services
    restart: unless-stopped
