services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:dev
    volumes:
      - ./data:/app/backend/data
    environment:
      - REDIS_URL=${REDIS_URL}/${REDIS_DB_WEBUI}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`open-webui.${DOMAIN}`)"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
    networks:
      - services
    restart: unless-stopped