services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    volumes:
      - ./data:/qdrant/storage
    ports:
      - "6333:6333"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.${DOMAIN}`)"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    networks:
      - services
    restart: unless-stopped