services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Bangkok
      # - JELLYFIN_PublishedServerUrl=http://jellyfin
    volumes:
      - ./config:/config
      - /mnt/hdd/media/tvshows:/data/tvshows
      - /mnt/hdd/media/movies:/data/movies
      - /mnt/hdd/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - services
    restart: unless-stopped
