services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TIMEZONE}
      - WEBUI_ADDRESS=0.0.0.0 
      - WEBUI_PORT=8080
      - WEBUI_CSRF_PROTECTION_ENABLED=false
      - TORRENTING_PORT=6881
    volumes:
      - ./data:/config
      - ${STORAGE_PATH}downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - services
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s