services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    volumes:
      - ./config:/opt/adguardhome/conf:ro # Configuration files
      - ./data:/opt/adguardhome/work # Persistent data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.${DOMAIN}`)"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
    networks:
      - services
    restart: unless-stopped