services:
  tududi:
    container_name: tududi
    image: chrisvel/tududi
    volumes:
      - ./data:/usr/src/app/tududi_db
    environment:
      - TUDUDI_USER_EMAIL=${TUDUDI_USER_EMAIL}
      - TUDUDI_USER_PASSWORD=${TUDUDI_USER_PASSWORD}
      - TUDUDI_SESSION_SECRET=${TUDUDI_SESSION_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tududi.rule=Host(`tududi.${DOMAIN}`)"
      - "traefik.http.services.tududi.loadbalancer.server.port=3002"
    networks:
      - frontend
      - backend
    restart: unless-stopped

networks:
  frontend:
    external: true
  backend:
    external: true