services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      - TZ=${TIMEZONE}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}/${REDIS_DB_HOMARR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/appdata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.${DOMAIN}`)"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
    networks:
      - services
    restart: unless-stopped