services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      - TZ=${TIMEZONE}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}/${REDIS_DB_HOMARR}
      - AUTH_PROVIDERS=oidc
      - AUTH_OIDC_CLIENT_ID=${HOMARR_POCKETID_ID}
      - AUTH_OIDC_CLIENT_SECRET=${HOMARR_POCKETID_SECRET}
      - AUTH_OIDC_ISSUER=https://pocket-id.${DOMAIN}
      - AUTH_OIDC_CLIENT_NAME="Pocket ID"
      - AUTH_OIDC_SCOPE_OVERWRITE=openid email profile groups
      - AUTH_OIDC_GROUPS_ATTRIBUTE=groups
      - AUTH_LOGOUT_REDIRECT_URL=https://pocket-id.${DOMAIN}
      - AUTH_OIDC_AUTO_LOGIN=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/appdata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.${DOMAIN}`)"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
    networks:
      - services
    restart: unless-stopped
