services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ${STORAGE_PATH}:/srv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.${DOMAIN}`)"
      - "traefik.http.routers.filebrowser.middlewares=auth@file"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - services
    restart: unless-stopped
